### ISSUE TITLE
ugly rail bed texure

### ISSUE THREAD

**Issue by Inonedn** [cam72cam/ImmersiveRailroading#546] opened 2019-02-18 14:17 UTC
there is a really ugly glitch where the rail bedding texture is squashed and not seamless

**Comment by cam72cam** [comment] 2019-02-24 00:41
It's by design since I have been too busy to remap the uv coordinates in the render

**Comment by cam72cam** [comment] 2019-04-07 11:55
There's no trivial way to do this, closing

**Closed by cam72cam** 2019-04-07 11:55 UTC
