### ISSUE TITLE
Make switchess great again!

### ISSUE THREAD

**Issue by dumboldoor** [cam72cam/ImmersiveRailroading#215] opened 2018-02-09 17:20 UTC
If possivle, it would be nice to have a feature that would allow you to control turn length and straight length separately.

Type: Switch
Railbed
Railbed fill
Quarters: 1-4
Turn length: 0-100
Straight length: 0-100
Track gauge: Brunel, Standard, Narrow, Minecraft, Model

As a side note, it would also be cool if we could have angled switches again, but it's fine if we don't.

**Comment by dumboldoor** [comment] 2018-02-09 17:35
+Three way switches would be amazing too

**Comment by cam72cam** [comment] 2018-02-10 00:36
Dupe of https://github.com/cam72cam/ImmersiveRailroading/issues/192 and https://github.com/cam72cam/ImmersiveRailroading/issues/99

**Closed by cam72cam** 2018-02-10 00:36 UTC
