### ISSUE TITLE
Incorrect/Incomplete Switch track animation

### ISSUE THREAD

**Issue by vladimir264** [cam72cam/ImmersiveRailroading#534] opened 2019-01-30 01:13 UTC
This was supposedly fixed in 1.0, however, both switch tracks are supposedly in the same position, however only the one from rails of war (smaller switch track) is correct in what rails are in what position
Also, in the top image, the train would go to the right (only with IR) and in the bottom image, the train would go strait, despite the rails showing otherwise. This, by the way, depends on what direction the track is placed (I'm not exactly sure on that very last directional dependent bit as I haven't done much testing)
![2019-01-29_20 11 43](https://user-images.githubusercontent.com/28151991/51951328-3341de00-2402-11e9-8392-e019d53fcc5e.png)
![2019-01-29_20 11 33](https://user-images.githubusercontent.com/28151991/51951329-3341de00-2402-11e9-94cc-8ee923c0d8f2.png)

**Comment by vladimir264** [comment] 2019-01-30 01:16
Also, a proper switching lever, like the one next to the ROW(Rails Of War) switch track has (it's a separate block by the way) should be added

**Comment by km00700** [comment] 2019-01-30 01:54
switch stands and multiple/alternate track models are in the works.

**Comment by vladimir264** [comment] 2019-01-30 05:11
> switch stands and multiple/alternate track models are in the works.

Any sort of estimate of when the switch stands in particular will be released? It is alright if that information is unavailable.

**Comment by cam72cam** [comment] 2019-04-07 11:59
Closing as dupe of https://github.com/cam72cam/ImmersiveRailroading/issues/55

**Closed by cam72cam** 2019-04-07 11:59 UTC
