### ISSUE TITLE
Client Rendering Crash in BetterQuesting UI

### ISSUE THREAD

**Issue by dragonshardz** [cam72cam/ImmersiveRailroading#457] opened 2018-10-24 05:47 UTC
[Crash report attached.](https://github.com/cam72cam/ImmersiveRailroading/files/2509097/crash-2018-10-23_22.44.50-client.txt)

**Comment by EweLoHD** [comment] 2018-10-24 08:56
Duplicate of #442

**Closed by EweLoHD** 2018-10-24 08:56 UTC
